{{ config(materialized='table', schema='STAGING') }}

WITH raw AS (
    SELECT * FROM {{ source('public', 'SRC_IPL_MATCH_DATA') }}
)
, cleaned AS (
    SELECT
        MATCH_ID,
        INITCAP(TRIM(CITY)) AS CITY,
        TRY_TO_DATE(DATES_1) AS MATCH_DATE,
        INITCAP(TRIM(SEASON)) AS SEASON,
        INITCAP(TRIM(VENUE)) AS VENUE,
        INITCAP(TRIM(MATCH_TYPE)) AS MATCH_TYPE,
        INITCAP(TRIM(MATCH_RESULT)) AS MATCH_RESULT,
        INITCAP(TRIM(WINNER)) AS WINNER,
        TRY_CAST(BY_WICKETS AS INT) AS BY_WICKETS,
        TRY_CAST(BY_RUNS AS INT) AS BY_RUNS,
        INITCAP(TRIM(METHOD)) AS METHOD,
        INITCAP(TRIM(PLAYER_OF_MATCH)) AS PLAYER_OF_MATCH,
        INITCAP(TRIM(TEAM_1)) AS TEAM_1,
        INITCAP(TRIM(TEAM_2)) AS TEAM_2,
        INITCAP(TRIM(TOSS_DECISION)) AS TOSS_DECISION,
        INITCAP(TRIM(TOSS_WINNER)) AS TOSS_WINNER,
        INITCAP(TRIM(UMPIRE_1)) AS UMPIRE_1,
        INITCAP(TRIM(UMPIRE_2)) AS UMPIRE_2
    FROM raw
    WHERE
        MATCH_ID IS NOT NULL
        AND TRIM(MATCH_ID) <> ''
        AND TRY_TO_DATE(DATES_1) IS NOT NULL
)
, deduped AS (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY MATCH_ID ORDER BY MATCH_DATE DESC) AS rn
    FROM cleaned
)
SELECT *
FROM deduped
WHERE rn = 1
